// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreatePost implements createPost operation.
	//
	// POST /posts
	CreatePost(ctx context.Context, req *CreatePostReq) (*Post, error)
	// DeletePost implements deletePost operation.
	//
	// DELETE /posts/{post_id}
	DeletePost(ctx context.Context, params DeletePostParams) (*DeletePostOK, error)
	// GetPost implements getPost operation.
	//
	// GET /posts/{post_id}
	GetPost(ctx context.Context, params GetPostParams) (*Post, error)
	// GetPosts implements getPosts operation.
	//
	// GET /posts
	GetPosts(ctx context.Context) ([]Post, error)
	// Signin implements signin operation.
	//
	// POST /signin
	Signin(ctx context.Context, req *SigninReq) (*SigninOK, error)
	// UpdatePost implements updatePost operation.
	//
	// PATCH /posts/{post_id}
	UpdatePost(ctx context.Context, req *UpdatePostReq, params UpdatePostParams) (*Post, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
