// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreatePostOperation OperationName = "CreatePost"
	DeletePostOperation OperationName = "DeletePost"
	GetPostOperation    OperationName = "GetPost"
	GetPostsOperation   OperationName = "GetPosts"
	SigninOperation     OperationName = "Signin"
	UpdatePostOperation OperationName = "UpdatePost"
)
