// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreatePost implements createPost operation.
//
// POST /posts
func (UnimplementedHandler) CreatePost(ctx context.Context, req *CreatePostReq) (r *Post, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePost implements deletePost operation.
//
// DELETE /posts/{post_id}
func (UnimplementedHandler) DeletePost(ctx context.Context, params DeletePostParams) (r *DeletePostOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPost implements getPost operation.
//
// GET /posts/{post_id}
func (UnimplementedHandler) GetPost(ctx context.Context, params GetPostParams) (r *Post, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPosts implements getPosts operation.
//
// GET /posts
func (UnimplementedHandler) GetPosts(ctx context.Context) (r []Post, _ error) {
	return r, ht.ErrNotImplemented
}

// Signin implements signin operation.
//
// POST /signin
func (UnimplementedHandler) Signin(ctx context.Context, req *SigninReq) (r *SigninOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePost implements updatePost operation.
//
// PATCH /posts/{post_id}
func (UnimplementedHandler) UpdatePost(ctx context.Context, req *UpdatePostReq, params UpdatePostParams) (r *Post, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
