// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

type CreatePostReq struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Content     string `json:"content"`
}

// GetTitle returns the value of Title.
func (s *CreatePostReq) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *CreatePostReq) GetDescription() string {
	return s.Description
}

// GetContent returns the value of Content.
func (s *CreatePostReq) GetContent() string {
	return s.Content
}

// SetTitle sets the value of Title.
func (s *CreatePostReq) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *CreatePostReq) SetDescription(val string) {
	s.Description = val
}

// SetContent sets the value of Content.
func (s *CreatePostReq) SetContent(val string) {
	s.Content = val
}

type DeletePostOK struct {
	Success OptBool `json:"success"`
}

// GetSuccess returns the value of Success.
func (s *DeletePostOK) GetSuccess() OptBool {
	return s.Success
}

// SetSuccess sets the value of Success.
func (s *DeletePostOK) SetSuccess(val OptBool) {
	s.Success = val
}

type Error struct {
	Error             string    `json:"error"`
	ErrorMinusKey     OptString `json:"error-key"`
	ErrorMinusDetails OptString `json:"error-details"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// GetErrorMinusKey returns the value of ErrorMinusKey.
func (s *Error) GetErrorMinusKey() OptString {
	return s.ErrorMinusKey
}

// GetErrorMinusDetails returns the value of ErrorMinusDetails.
func (s *Error) GetErrorMinusDetails() OptString {
	return s.ErrorMinusDetails
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

// SetErrorMinusKey sets the value of ErrorMinusKey.
func (s *Error) SetErrorMinusKey(val OptString) {
	s.ErrorMinusKey = val
}

// SetErrorMinusDetails sets the value of ErrorMinusDetails.
func (s *Error) SetErrorMinusDetails(val OptString) {
	s.ErrorMinusDetails = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Post
type Post struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Content     string `json:"content"`
}

// GetID returns the value of ID.
func (s *Post) GetID() int {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Post) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Post) GetDescription() string {
	return s.Description
}

// GetContent returns the value of Content.
func (s *Post) GetContent() string {
	return s.Content
}

// SetID sets the value of ID.
func (s *Post) SetID(val int) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Post) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Post) SetDescription(val string) {
	s.Description = val
}

// SetContent sets the value of Content.
func (s *Post) SetContent(val string) {
	s.Content = val
}

type SigninOK struct {
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *SigninOK) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *SigninOK) SetToken(val string) {
	s.Token = val
}

type SigninReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *SigninReq) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *SigninReq) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *SigninReq) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *SigninReq) SetPassword(val string) {
	s.Password = val
}

type UpdatePostReq struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Content     string `json:"content"`
}

// GetTitle returns the value of Title.
func (s *UpdatePostReq) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *UpdatePostReq) GetDescription() string {
	return s.Description
}

// GetContent returns the value of Content.
func (s *UpdatePostReq) GetContent() string {
	return s.Content
}

// SetTitle sets the value of Title.
func (s *UpdatePostReq) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *UpdatePostReq) SetDescription(val string) {
	s.Description = val
}

// SetContent sets the value of Content.
func (s *UpdatePostReq) SetContent(val string) {
	s.Content = val
}
