// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateNewAlbumOperation         OperationName = "CreateNewAlbum"
	CreateNewTrackOperation         OperationName = "CreateNewTrack"
	DeleteAlbumOperation            OperationName = "DeleteAlbum"
	DeleteAuthorToAlbumOperation    OperationName = "DeleteAuthorToAlbum"
	DeleteAuthorToTrackOperation    OperationName = "DeleteAuthorToTrack"
	DeleteTrackOperation            OperationName = "DeleteTrack"
	GetAlbumFromIdOperation         OperationName = "GetAlbumFromId"
	GetAlbumFromTrackOperation      OperationName = "GetAlbumFromTrack"
	GetAlbumsFromAuthorOperation    OperationName = "GetAlbumsFromAuthor"
	GetAllAlbumsOperation           OperationName = "GetAllAlbums"
	GetAllAuthorsOperation          OperationName = "GetAllAuthors"
	GetAllTracksOperation           OperationName = "GetAllTracks"
	GetAuthorOperation              OperationName = "GetAuthor"
	GetAuthorsFromAlbumOperation    OperationName = "GetAuthorsFromAlbum"
	GetAuthorsFromTrackOperation    OperationName = "GetAuthorsFromTrack"
	GetTrackByIdOperation           OperationName = "GetTrackById"
	GetTracksFromAlbumOperation     OperationName = "GetTracksFromAlbum"
	GetTracksFromAuthorOperation    OperationName = "GetTracksFromAuthor"
	PushNewAuthorFromAlbumOperation OperationName = "PushNewAuthorFromAlbum"
	PushNewAuthorFromTrackOperation OperationName = "PushNewAuthorFromTrack"
	SigninOperation                 OperationName = "Signin"
	UpdateAlbumOperation            OperationName = "UpdateAlbum"
	UpdateTrackOperation            OperationName = "UpdateTrack"
)
