// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateNewAlbum implements createNewAlbum operation.
//
// POST /albums
func (UnimplementedHandler) CreateNewAlbum(ctx context.Context, req *CreateNewAlbumReq) (r *Album, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateNewTrack implements createNewTrack operation.
//
// POST /tracks
func (UnimplementedHandler) CreateNewTrack(ctx context.Context, req *CreateNewTrackReq) (r *Track, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAlbum implements deleteAlbum operation.
//
// DELETE /albums/{id_album}
func (UnimplementedHandler) DeleteAlbum(ctx context.Context, params DeleteAlbumParams) (r *DeleteAlbumNoContent, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAuthorToAlbum implements deleteAuthorToAlbum operation.
//
// DELETE /albums/{id_album}/authors/{id_author}
func (UnimplementedHandler) DeleteAuthorToAlbum(ctx context.Context, params DeleteAuthorToAlbumParams) (r *DeleteAuthorToAlbumNoContent, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAuthorToTrack implements deleteAuthorToTrack operation.
//
// DELETE /tracks/{id_track}/authors/{id_author}
func (UnimplementedHandler) DeleteAuthorToTrack(ctx context.Context, params DeleteAuthorToTrackParams) (r *DeleteAuthorToTrackNoContent, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTrack implements deleteTrack operation.
//
// DELETE /tracks/{id_track}
func (UnimplementedHandler) DeleteTrack(ctx context.Context, params DeleteTrackParams) (r *DeleteTrackNoContent, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAlbumFromId implements getAlbumFromId operation.
//
// GET /albums/{id_album}
func (UnimplementedHandler) GetAlbumFromId(ctx context.Context, params GetAlbumFromIdParams) (r *Album, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAlbumFromTrack implements getAlbumFromTrack operation.
//
// GET /tracks/{id_track}/album
func (UnimplementedHandler) GetAlbumFromTrack(ctx context.Context, params GetAlbumFromTrackParams) (r *Album, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAlbumsFromAuthor implements getAlbumsFromAuthor operation.
//
// GET /authors/{id_author}/albums
func (UnimplementedHandler) GetAlbumsFromAuthor(ctx context.Context, params GetAlbumsFromAuthorParams) (r []Album, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllAlbums implements getAllAlbums operation.
//
// GET /albums
func (UnimplementedHandler) GetAllAlbums(ctx context.Context) (r []Album, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllAuthors implements getAllAuthors operation.
//
// GET /authors
func (UnimplementedHandler) GetAllAuthors(ctx context.Context) (r []Author, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllTracks implements getAllTracks operation.
//
// GET /tracks
func (UnimplementedHandler) GetAllTracks(ctx context.Context) (r []Track, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuthor implements getAuthor operation.
//
// GET /authors/{id_author}
func (UnimplementedHandler) GetAuthor(ctx context.Context, params GetAuthorParams) (r *Author, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuthorsFromAlbum implements getAuthorsFromAlbum operation.
//
// GET /albums/{id_album}/authors
func (UnimplementedHandler) GetAuthorsFromAlbum(ctx context.Context, params GetAuthorsFromAlbumParams) (r []Author, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuthorsFromTrack implements getAuthorsFromTrack operation.
//
// GET /tracks/{id_track}/authors
func (UnimplementedHandler) GetAuthorsFromTrack(ctx context.Context, params GetAuthorsFromTrackParams) (r []Author, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrackById implements getTrackById operation.
//
// GET /tracks/{id_track}
func (UnimplementedHandler) GetTrackById(ctx context.Context, params GetTrackByIdParams) (r *Track, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTracksFromAlbum implements getTracksFromAlbum operation.
//
// GET /albums/{id_album}/tracks
func (UnimplementedHandler) GetTracksFromAlbum(ctx context.Context, params GetTracksFromAlbumParams) (r []Track, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTracksFromAuthor implements getTracksFromAuthor operation.
//
// GET /authors/{id_author}/tracks
func (UnimplementedHandler) GetTracksFromAuthor(ctx context.Context, params GetTracksFromAuthorParams) (r []Track, _ error) {
	return r, ht.ErrNotImplemented
}

// PushNewAuthorFromAlbum implements pushNewAuthorFromAlbum operation.
//
// PATCH /albums/{id_album}/authors
func (UnimplementedHandler) PushNewAuthorFromAlbum(ctx context.Context, req *PushNewAuthorFromAlbumReq, params PushNewAuthorFromAlbumParams) (r *PushNewAuthorFromAlbumOK, _ error) {
	return r, ht.ErrNotImplemented
}

// PushNewAuthorFromTrack implements pushNewAuthorFromTrack operation.
//
// PATCH /tracks/{id_track}/authors
func (UnimplementedHandler) PushNewAuthorFromTrack(ctx context.Context, req *PushNewAuthorFromTrackReq, params PushNewAuthorFromTrackParams) (r *PushNewAuthorFromTrackOK, _ error) {
	return r, ht.ErrNotImplemented
}

// Signin implements signin operation.
//
// POST /signin
func (UnimplementedHandler) Signin(ctx context.Context, req *SigninReq) (r *SigninOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAlbum implements updateAlbum operation.
//
// PATCH /albums/{id_album}
func (UnimplementedHandler) UpdateAlbum(ctx context.Context, req *UpdateAlbumReq, params UpdateAlbumParams) (r *Album, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTrack implements updateTrack operation.
//
// PATCH /tracks/{id_track}
func (UnimplementedHandler) UpdateTrack(ctx context.Context, req *UpdateTrackReq, params UpdateTrackParams) (r *Track, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
