// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteAlbumParams is parameters of deleteAlbum operation.
type DeleteAlbumParams struct {
	IDAlbum int
}

func unpackDeleteAlbumParams(packed middleware.Parameters) (params DeleteAlbumParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_album",
			In:   "path",
		}
		params.IDAlbum = packed[key].(int)
	}
	return params
}

func decodeDeleteAlbumParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteAlbumParams, _ error) {
	// Decode path: id_album.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_album",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAlbum = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_album",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteAuthorToAlbumParams is parameters of deleteAuthorToAlbum operation.
type DeleteAuthorToAlbumParams struct {
	IDAlbum  int
	IDAuthor int
}

func unpackDeleteAuthorToAlbumParams(packed middleware.Parameters) (params DeleteAuthorToAlbumParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_album",
			In:   "path",
		}
		params.IDAlbum = packed[key].(int)
	}
	{
		key := middleware.ParameterKey{
			Name: "id_author",
			In:   "path",
		}
		params.IDAuthor = packed[key].(int)
	}
	return params
}

func decodeDeleteAuthorToAlbumParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteAuthorToAlbumParams, _ error) {
	// Decode path: id_album.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_album",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAlbum = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_album",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: id_author.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_author",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAuthor = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_author",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteAuthorToTrackParams is parameters of deleteAuthorToTrack operation.
type DeleteAuthorToTrackParams struct {
	IDTrack  int
	IDAuthor int
}

func unpackDeleteAuthorToTrackParams(packed middleware.Parameters) (params DeleteAuthorToTrackParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_track",
			In:   "path",
		}
		params.IDTrack = packed[key].(int)
	}
	{
		key := middleware.ParameterKey{
			Name: "id_author",
			In:   "path",
		}
		params.IDAuthor = packed[key].(int)
	}
	return params
}

func decodeDeleteAuthorToTrackParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteAuthorToTrackParams, _ error) {
	// Decode path: id_track.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_track",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDTrack = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_track",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: id_author.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_author",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAuthor = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_author",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteTrackParams is parameters of deleteTrack operation.
type DeleteTrackParams struct {
	IDTrack int
}

func unpackDeleteTrackParams(packed middleware.Parameters) (params DeleteTrackParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_track",
			In:   "path",
		}
		params.IDTrack = packed[key].(int)
	}
	return params
}

func decodeDeleteTrackParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteTrackParams, _ error) {
	// Decode path: id_track.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_track",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDTrack = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_track",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAlbumFromIdParams is parameters of getAlbumFromId operation.
type GetAlbumFromIdParams struct {
	IDAlbum int
}

func unpackGetAlbumFromIdParams(packed middleware.Parameters) (params GetAlbumFromIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_album",
			In:   "path",
		}
		params.IDAlbum = packed[key].(int)
	}
	return params
}

func decodeGetAlbumFromIdParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAlbumFromIdParams, _ error) {
	// Decode path: id_album.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_album",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAlbum = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_album",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAlbumFromTrackParams is parameters of getAlbumFromTrack operation.
type GetAlbumFromTrackParams struct {
	IDTrack int
}

func unpackGetAlbumFromTrackParams(packed middleware.Parameters) (params GetAlbumFromTrackParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_track",
			In:   "path",
		}
		params.IDTrack = packed[key].(int)
	}
	return params
}

func decodeGetAlbumFromTrackParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAlbumFromTrackParams, _ error) {
	// Decode path: id_track.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_track",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDTrack = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_track",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAlbumsFromAuthorParams is parameters of getAlbumsFromAuthor operation.
type GetAlbumsFromAuthorParams struct {
	IDAuthor int
}

func unpackGetAlbumsFromAuthorParams(packed middleware.Parameters) (params GetAlbumsFromAuthorParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_author",
			In:   "path",
		}
		params.IDAuthor = packed[key].(int)
	}
	return params
}

func decodeGetAlbumsFromAuthorParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAlbumsFromAuthorParams, _ error) {
	// Decode path: id_author.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_author",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAuthor = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_author",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAuthorParams is parameters of getAuthor operation.
type GetAuthorParams struct {
	IDAuthor int
}

func unpackGetAuthorParams(packed middleware.Parameters) (params GetAuthorParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_author",
			In:   "path",
		}
		params.IDAuthor = packed[key].(int)
	}
	return params
}

func decodeGetAuthorParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAuthorParams, _ error) {
	// Decode path: id_author.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_author",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAuthor = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_author",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAuthorsFromAlbumParams is parameters of getAuthorsFromAlbum operation.
type GetAuthorsFromAlbumParams struct {
	IDAlbum int
}

func unpackGetAuthorsFromAlbumParams(packed middleware.Parameters) (params GetAuthorsFromAlbumParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_album",
			In:   "path",
		}
		params.IDAlbum = packed[key].(int)
	}
	return params
}

func decodeGetAuthorsFromAlbumParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAuthorsFromAlbumParams, _ error) {
	// Decode path: id_album.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_album",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAlbum = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_album",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAuthorsFromTrackParams is parameters of getAuthorsFromTrack operation.
type GetAuthorsFromTrackParams struct {
	IDTrack int
}

func unpackGetAuthorsFromTrackParams(packed middleware.Parameters) (params GetAuthorsFromTrackParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_track",
			In:   "path",
		}
		params.IDTrack = packed[key].(int)
	}
	return params
}

func decodeGetAuthorsFromTrackParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAuthorsFromTrackParams, _ error) {
	// Decode path: id_track.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_track",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDTrack = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_track",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTrackByIdParams is parameters of getTrackById operation.
type GetTrackByIdParams struct {
	IDTrack int
}

func unpackGetTrackByIdParams(packed middleware.Parameters) (params GetTrackByIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_track",
			In:   "path",
		}
		params.IDTrack = packed[key].(int)
	}
	return params
}

func decodeGetTrackByIdParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTrackByIdParams, _ error) {
	// Decode path: id_track.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_track",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDTrack = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_track",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTracksFromAlbumParams is parameters of getTracksFromAlbum operation.
type GetTracksFromAlbumParams struct {
	IDAlbum int
}

func unpackGetTracksFromAlbumParams(packed middleware.Parameters) (params GetTracksFromAlbumParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_album",
			In:   "path",
		}
		params.IDAlbum = packed[key].(int)
	}
	return params
}

func decodeGetTracksFromAlbumParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTracksFromAlbumParams, _ error) {
	// Decode path: id_album.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_album",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAlbum = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_album",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTracksFromAuthorParams is parameters of getTracksFromAuthor operation.
type GetTracksFromAuthorParams struct {
	IDAuthor int
}

func unpackGetTracksFromAuthorParams(packed middleware.Parameters) (params GetTracksFromAuthorParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_author",
			In:   "path",
		}
		params.IDAuthor = packed[key].(int)
	}
	return params
}

func decodeGetTracksFromAuthorParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTracksFromAuthorParams, _ error) {
	// Decode path: id_author.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_author",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAuthor = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_author",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// PushNewAuthorFromAlbumParams is parameters of pushNewAuthorFromAlbum operation.
type PushNewAuthorFromAlbumParams struct {
	IDAlbum int
}

func unpackPushNewAuthorFromAlbumParams(packed middleware.Parameters) (params PushNewAuthorFromAlbumParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_album",
			In:   "path",
		}
		params.IDAlbum = packed[key].(int)
	}
	return params
}

func decodePushNewAuthorFromAlbumParams(args [1]string, argsEscaped bool, r *http.Request) (params PushNewAuthorFromAlbumParams, _ error) {
	// Decode path: id_album.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_album",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAlbum = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_album",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// PushNewAuthorFromTrackParams is parameters of pushNewAuthorFromTrack operation.
type PushNewAuthorFromTrackParams struct {
	IDTrack int
}

func unpackPushNewAuthorFromTrackParams(packed middleware.Parameters) (params PushNewAuthorFromTrackParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_track",
			In:   "path",
		}
		params.IDTrack = packed[key].(int)
	}
	return params
}

func decodePushNewAuthorFromTrackParams(args [1]string, argsEscaped bool, r *http.Request) (params PushNewAuthorFromTrackParams, _ error) {
	// Decode path: id_track.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_track",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDTrack = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_track",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateAlbumParams is parameters of updateAlbum operation.
type UpdateAlbumParams struct {
	IDAlbum int
}

func unpackUpdateAlbumParams(packed middleware.Parameters) (params UpdateAlbumParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_album",
			In:   "path",
		}
		params.IDAlbum = packed[key].(int)
	}
	return params
}

func decodeUpdateAlbumParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateAlbumParams, _ error) {
	// Decode path: id_album.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_album",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDAlbum = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_album",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateTrackParams is parameters of updateTrack operation.
type UpdateTrackParams struct {
	IDTrack int
}

func unpackUpdateTrackParams(packed middleware.Parameters) (params UpdateTrackParams) {
	{
		key := middleware.ParameterKey{
			Name: "id_track",
			In:   "path",
		}
		params.IDTrack = packed[key].(int)
	}
	return params
}

func decodeUpdateTrackParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateTrackParams, _ error) {
	// Decode path: id_track.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id_track",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.IDTrack = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id_track",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
