// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type AddAuthorToAlbumOK struct {
	Success OptBool `json:"success"`
}

// GetSuccess returns the value of Success.
func (s *AddAuthorToAlbumOK) GetSuccess() OptBool {
	return s.Success
}

// SetSuccess sets the value of Success.
func (s *AddAuthorToAlbumOK) SetSuccess(val OptBool) {
	s.Success = val
}

type AddAuthorToAlbumReq struct {
	IDAuthor int `json:"id_author"`
}

// GetIDAuthor returns the value of IDAuthor.
func (s *AddAuthorToAlbumReq) GetIDAuthor() int {
	return s.IDAuthor
}

// SetIDAuthor sets the value of IDAuthor.
func (s *AddAuthorToAlbumReq) SetIDAuthor(val int) {
	s.IDAuthor = val
}

// Ref: #/components/schemas/Album
type Album struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

// GetID returns the value of ID.
func (s *Album) GetID() int {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Album) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Album) GetDescription() string {
	return s.Description
}

// SetID sets the value of ID.
func (s *Album) SetID(val int) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Album) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Album) SetDescription(val string) {
	s.Description = val
}

// Ref: #/components/schemas/Author
type Author struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Name     string `json:"name"`
}

// GetID returns the value of ID.
func (s *Author) GetID() int {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *Author) GetUsername() string {
	return s.Username
}

// GetName returns the value of Name.
func (s *Author) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Author) SetID(val int) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *Author) SetUsername(val string) {
	s.Username = val
}

// SetName sets the value of Name.
func (s *Author) SetName(val string) {
	s.Name = val
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

type CreateNewAlbumReq struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

// GetTitle returns the value of Title.
func (s *CreateNewAlbumReq) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *CreateNewAlbumReq) GetDescription() string {
	return s.Description
}

// SetTitle sets the value of Title.
func (s *CreateNewAlbumReq) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *CreateNewAlbumReq) SetDescription(val string) {
	s.Description = val
}

type CreateNewTrackReq struct {
	Name     string `json:"name"`
	IDAlbum  int    `json:"id_album"`
	IDAuthor int    `json:"id_author"`
}

// GetName returns the value of Name.
func (s *CreateNewTrackReq) GetName() string {
	return s.Name
}

// GetIDAlbum returns the value of IDAlbum.
func (s *CreateNewTrackReq) GetIDAlbum() int {
	return s.IDAlbum
}

// GetIDAuthor returns the value of IDAuthor.
func (s *CreateNewTrackReq) GetIDAuthor() int {
	return s.IDAuthor
}

// SetName sets the value of Name.
func (s *CreateNewTrackReq) SetName(val string) {
	s.Name = val
}

// SetIDAlbum sets the value of IDAlbum.
func (s *CreateNewTrackReq) SetIDAlbum(val int) {
	s.IDAlbum = val
}

// SetIDAuthor sets the value of IDAuthor.
func (s *CreateNewTrackReq) SetIDAuthor(val int) {
	s.IDAuthor = val
}

// DeleteAlbumNoContent is response for DeleteAlbum operation.
type DeleteAlbumNoContent struct{}

// DeleteAuthorFromAlbumNoContent is response for DeleteAuthorFromAlbum operation.
type DeleteAuthorFromAlbumNoContent struct{}

// DeleteTrackNoContent is response for DeleteTrack operation.
type DeleteTrackNoContent struct{}

type Error struct {
	Error             string    `json:"error"`
	ErrorMinusKey     OptString `json:"error-key"`
	ErrorMinusDetails OptString `json:"error-details"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// GetErrorMinusKey returns the value of ErrorMinusKey.
func (s *Error) GetErrorMinusKey() OptString {
	return s.ErrorMinusKey
}

// GetErrorMinusDetails returns the value of ErrorMinusDetails.
func (s *Error) GetErrorMinusDetails() OptString {
	return s.ErrorMinusDetails
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

// SetErrorMinusKey sets the value of ErrorMinusKey.
func (s *Error) SetErrorMinusKey(val OptString) {
	s.ErrorMinusKey = val
}

// SetErrorMinusDetails sets the value of ErrorMinusDetails.
func (s *Error) SetErrorMinusDetails(val OptString) {
	s.ErrorMinusDetails = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RefreshReq struct {
	RefreshToken string `json:"refresh_token"`
}

// GetRefreshToken returns the value of RefreshToken.
func (s *RefreshReq) GetRefreshToken() string {
	return s.RefreshToken
}

// SetRefreshToken sets the value of RefreshToken.
func (s *RefreshReq) SetRefreshToken(val string) {
	s.RefreshToken = val
}

type SigninReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *SigninReq) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *SigninReq) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *SigninReq) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *SigninReq) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/TokenPair
type TokenPair struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// GetAccessToken returns the value of AccessToken.
func (s *TokenPair) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *TokenPair) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *TokenPair) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *TokenPair) SetRefreshToken(val string) {
	s.RefreshToken = val
}

// Ref: #/components/schemas/Track
type Track struct {
	ID      int    `json:"id"`
	Name    string `json:"name"`
	IDAlbum int    `json:"id_album"`
}

// GetID returns the value of ID.
func (s *Track) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *Track) GetName() string {
	return s.Name
}

// GetIDAlbum returns the value of IDAlbum.
func (s *Track) GetIDAlbum() int {
	return s.IDAlbum
}

// SetID sets the value of ID.
func (s *Track) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Track) SetName(val string) {
	s.Name = val
}

// SetIDAlbum sets the value of IDAlbum.
func (s *Track) SetIDAlbum(val int) {
	s.IDAlbum = val
}

type UpdateAlbumReq struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

// GetTitle returns the value of Title.
func (s *UpdateAlbumReq) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *UpdateAlbumReq) GetDescription() string {
	return s.Description
}

// SetTitle sets the value of Title.
func (s *UpdateAlbumReq) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *UpdateAlbumReq) SetDescription(val string) {
	s.Description = val
}

type UpdateTrackReq struct {
	Name    string `json:"name"`
	IDAlbum int    `json:"id_album"`
}

// GetName returns the value of Name.
func (s *UpdateTrackReq) GetName() string {
	return s.Name
}

// GetIDAlbum returns the value of IDAlbum.
func (s *UpdateTrackReq) GetIDAlbum() int {
	return s.IDAlbum
}

// SetName sets the value of Name.
func (s *UpdateTrackReq) SetName(val string) {
	s.Name = val
}

// SetIDAlbum sets the value of IDAlbum.
func (s *UpdateTrackReq) SetIDAlbum(val int) {
	s.IDAlbum = val
}
