// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddAuthorToAlbum implements addAuthorToAlbum operation.
	//
	// PATCH /albums/{id_album}/authors
	AddAuthorToAlbum(ctx context.Context, req *AddAuthorToAlbumReq, params AddAuthorToAlbumParams) (*AddAuthorToAlbumOK, error)
	// CreateNewAlbum implements createNewAlbum operation.
	//
	// POST /albums
	CreateNewAlbum(ctx context.Context, req *CreateNewAlbumReq) (*Album, error)
	// CreateNewTrack implements createNewTrack operation.
	//
	// POST /tracks
	CreateNewTrack(ctx context.Context, req *CreateNewTrackReq) (*Track, error)
	// DeleteAlbum implements deleteAlbum operation.
	//
	// DELETE /albums/{id_album}
	DeleteAlbum(ctx context.Context, params DeleteAlbumParams) error
	// DeleteAuthorFromAlbum implements deleteAuthorFromAlbum operation.
	//
	// DELETE /albums/{id_album}/authors/{id_author}
	DeleteAuthorFromAlbum(ctx context.Context, params DeleteAuthorFromAlbumParams) error
	// DeleteTrack implements deleteTrack operation.
	//
	// DELETE /tracks/{id_track}
	DeleteTrack(ctx context.Context, params DeleteTrackParams) error
	// GetAlbumFromId implements getAlbumFromId operation.
	//
	// GET /albums/{id_album}
	GetAlbumFromId(ctx context.Context, params GetAlbumFromIdParams) (*Album, error)
	// GetAlbumFromTrack implements getAlbumFromTrack operation.
	//
	// GET /tracks/{id_track}/album
	GetAlbumFromTrack(ctx context.Context, params GetAlbumFromTrackParams) (*Album, error)
	// GetAlbumsFromAuthor implements getAlbumsFromAuthor operation.
	//
	// GET /authors/{id_author}/albums
	GetAlbumsFromAuthor(ctx context.Context, params GetAlbumsFromAuthorParams) ([]Album, error)
	// GetAllAlbums implements getAllAlbums operation.
	//
	// GET /albums
	GetAllAlbums(ctx context.Context) ([]Album, error)
	// GetAllAuthors implements getAllAuthors operation.
	//
	// GET /authors
	GetAllAuthors(ctx context.Context) ([]Author, error)
	// GetAllTracks implements getAllTracks operation.
	//
	// GET /tracks
	GetAllTracks(ctx context.Context) ([]Track, error)
	// GetAuthor implements getAuthor operation.
	//
	// GET /authors/{id_author}
	GetAuthor(ctx context.Context, params GetAuthorParams) (*Author, error)
	// GetAuthorsFromAlbum implements getAuthorsFromAlbum operation.
	//
	// GET /albums/{id_album}/authors
	GetAuthorsFromAlbum(ctx context.Context, params GetAuthorsFromAlbumParams) ([]Author, error)
	// GetAuthorsFromTrack implements getAuthorsFromTrack operation.
	//
	// GET /tracks/{id_track}/authors
	GetAuthorsFromTrack(ctx context.Context, params GetAuthorsFromTrackParams) ([]Author, error)
	// GetTrackById implements getTrackById operation.
	//
	// GET /tracks/{id_track}
	GetTrackById(ctx context.Context, params GetTrackByIdParams) (*Track, error)
	// GetTracksFromAlbum implements getTracksFromAlbum operation.
	//
	// GET /albums/{id_album}/tracks
	GetTracksFromAlbum(ctx context.Context, params GetTracksFromAlbumParams) ([]Track, error)
	// GetTracksFromAuthor implements getTracksFromAuthor operation.
	//
	// GET /authors/{id_author}/tracks
	GetTracksFromAuthor(ctx context.Context, params GetTracksFromAuthorParams) ([]Track, error)
	// Refresh implements refresh operation.
	//
	// POST /refresh
	Refresh(ctx context.Context, req *RefreshReq) (*TokenPair, error)
	// Signin implements signin operation.
	//
	// POST /signin
	Signin(ctx context.Context, req *SigninReq) (*TokenPair, error)
	// UpdateAlbum implements updateAlbum operation.
	//
	// PATCH /albums/{id_album}
	UpdateAlbum(ctx context.Context, req *UpdateAlbumReq, params UpdateAlbumParams) (*Album, error)
	// UpdateTrack implements updateTrack operation.
	//
	// PATCH /tracks/{id_track}
	UpdateTrack(ctx context.Context, req *UpdateTrackReq, params UpdateTrackParams) (*Track, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
